"""empty message

Revision ID: 330cc521dcd6
Revises: 
Create Date: 2023-04-13 09:29:01.682728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '330cc521dcd6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('creation_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.drop_constraint('users_password_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('users_password_key', ['password'])
        batch_op.alter_column('creation_date',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
